### ISSUE TITLE
Build error on ghc-8.4.3

### ISSUE THREAD

**Issue by alogic0** [feuerbach/yaml-combinators#4]
I'm not sure whose issue it is, because I tried to compile on a freshly installed GHC 8.4.3 on Windows. I used `cabal-install` and it successfully built all of the long chain of dependecies. But on the `yaml-combinators`  it throwed this error:
```
src\Data\Yaml\Combinators.hs:210:10: error:
    * No instance for (Semigroup (ParserComponent a fs))
        arising from the superclasses of an instance declaration
    * In the instance declaration for `Monoid (ParserComponent a fs)'
    |
210 | instance Monoid (ParserComponent a fs) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src\Data\Yaml\Combinators.hs:223:10: error:
    * No instance for (Semigroup (Parser a))
        arising from the superclasses of an instance declaration
      There are instances for similar types:
        instance Semigroup
                   (attoparsec-0.13.2.2:Data.Attoparsec.Internal.Types.Parser i a)
          -- Defined in `attoparsec-0.13.2.2:Data.Attoparsec.Internal.Types'
        instance Semigroup
                   (aeson-1.3.1.1:Data.Aeson.Types.Internal.Parser a)
          -- Defined in `aeson-1.3.1.1:Data.Aeson.Types.Internal'
    * In the instance declaration for `Monoid (Parser a)'
    |
223 | instance Monoid (Parser a) where
    |          ^^^^^^^^^^^^^^^^^
```

**Comment by UnkindPartition** [comment]
Thanks for the report. Fixed in yaml-combinators-1.1.1.1.
